[tool.poetry]
name = "Weblog"
version = "0.1"
description = "FastAPI and PostrgeSQL site, supported with Docker and poetry"
authors = ["Blinov Ilya"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "~0.11.3"
fastapi = "~0.68.0"
