"""Create DB

Revision ID: 28f467282c51
Revises: ec46ad7fc181
Create Date: 2022-08-31 10:20:07.197050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f467282c51'
down_revision = 'ec46ad7fc181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_id', table_name='recipe')
    op.drop_index('ix_recipe_url', table_name='recipe')
    op.drop_table('recipe')
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'is_moderator')
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('submitter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], name='recipe_submitter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_pkey')
    )
    op.create_index('ix_recipe_url', 'recipe', ['url'], unique=False)
    op.create_index('ix_recipe_id', 'recipe', ['id'], unique=False)
    # ### end Alembic commands ###
